import type { GamesPageConfig } from "@/types/gameConfig";

export const gamesPageConfig: GamesPageConfig = {
	title: "游戏",
	description: "记录玩过和正在玩的游戏",
	categories: [
		{
			id: "gacha",
			name: "二游",
			description: "“天河泄梦”",
			icon: "material-symbols:auto-awesome-rounded",
			items: [
				{
					id: "genshin-impact",
					title: "原神",
					year: "2020",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/1a/22/284157_zgv97.jpg",
					url: "https://bgm.tv/subject/284157",
					score: 5.2,
					tags: ["miHoYo", "开放世界"],
				},
				{
					id: "honkai-star-rail",
					title: "崩坏：星穹铁道",
					year: "2023",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/d2/c9/360097_z4dYA.jpg",
					url: "https://bgm.tv/subject/360097",
					score: 5.9,
					tags: ["miHoYo", "回合制"],
				},
				{
					id: "wuthering-waves",
					title: "鸣潮",
					year: "2024",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/2e/ef/385208_shW2q.jpg",
					url: "https://bgm.tv/subject/385208",
					score: 6.2,
					tags: ["库洛游戏", "开放世界", "ARPG"],
				},
				{
					id: "zenless-zone-zero",
					title: "绝区零",
					year: "2024",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/90/24/380974_Kn8bt.jpg",
					url: "https://bgm.tv/subject/380974",
					score: 5.3,
					tags: ["miHoYo", "ACT"],
				},
				{
					id: "neverness-to-everness",
					title: "异环",
					year: "2026",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/e7/1f/503983_6TzsC.jpg",
					url: "https://bgm.tv/subject/503983",
					score: 5.6,
					tags: ["开放世界", "PC"],
				},
			],
		},
		{
			id: "aaa",
			name: "3A",
			description: "走过公路、神话与夜之城",
			icon: "material-symbols:sports-esports-rounded",
			items: [
				{
					id: "forza-horizon-4",
					title: "极限竞速：地平线4",
					year: "2018",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/47/49/235675_MDomS.jpg",
					url: "https://bgm.tv/subject/235675",
					score: 7.9,
					tags: ["赛车", "PC", "开放世界"],
				},
				{
					id: "forza-horizon-5",
					title: "极限竞速：地平线5",
					year: "2021",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/53/b4/338909_ZBP7p.jpg",
					url: "https://bgm.tv/subject/338909",
					score: 7.5,
					tags: ["赛车", "PC", "开放世界"],
				},
				{
					id: "black-myth-wukong",
					title: "黑神话：悟空",
					year: "2024",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/be/b4/313495_oVVzV.jpg",
					url: "https://bgm.tv/subject/313495",
					score: 7.8,
					tags: ["国产", "ARPG", "西游"],
				},
				{
					id: "cyberpunk-2077",
					title: "赛博朋克2077",
					year: "2020",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/9a/c2/65759_fhutt.jpg",
					url: "https://bgm.tv/subject/65759",
					score: 7.4,
					tags: ["RPG", "PC", "开放世界"],
				},
				{
					id: "clair-obscur-expedition-33",
					title: "33号远征队：光与影",
					year: "2025",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/41/87/498449_7Q9wH.jpg",
					url: "https://bgm.tv/subject/498449",
					score: 7.1,
					tags: ["JRPG", "回合制", "PC"],
				},
			],
		},
		{
			id: "other",
			name: "其他游戏",
			description: "我的”世界“",
			icon: "material-symbols:stacks-rounded",
			trailingEllipsis: true,
			items: [
				{
					id: "minecraft",
					title: "Minecraft",
					year: "2011",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/ca/a0/12596_8YuNn.jpg",
					url: "https://bgm.tv/subject/12596",
					score: 8.9,
					tags: ["沙盒", "自由度", "PC"],
				},
				{
					id: "undertale",
					title: "Undertale",
					year: "2015",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/68/52/147713_r51UK.jpg",
					url: "https://bgm.tv/subject/147713",
					score: 8.3,
					tags: ["RPG", "独立游戏", "像素"],
				},
				{
					id: "monument-valley-series",
					title: "纪念碑谷（系列）",
					year: "2014",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/a1/d1/101922_DZJzr.jpg",
					url: "https://bgm.tv/subject/101922",
					score: 7.8,
					tags: ["解谜", "独立游戏", "几何"],
				},
				{
					id: "spiderheck",
					title: "SpiderHeck",
					year: "2022",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/d8/72/402333_z806B.jpg",
					url: "https://bgm.tv/subject/402333",
					score: 7,
					tags: ["多人", "派对", "PC"],
				},
				{
					id: "terraria",
					title: "Terraria",
					year: "2011",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/59/ee/17852_7H99Q.jpg",
					url: "https://bgm.tv/subject/17852",
					score: 8.3,
					tags: ["沙盒", "独立游戏", "像素"],
				},
				{
					id: "stardew-valley",
					title: "星露谷物语",
					year: "2016",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/f6/87/172808_rf2iX.jpg",
					url: "https://bgm.tv/subject/172808",
					score: 7.8,
					tags: ["模拟经营", "独立游戏", "像素"],
				},
				{
					id: "civilization-vi",
					title: "文明VI",
					year: "2016",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/2f/38/182389_knNHp.jpg",
					url: "https://bgm.tv/subject/182389",
					score: 7.4,
					tags: ["SLG", "策略", "PC"],
				},
				{
					id: "plants-vs-zombies-garden-warfare",
					title: "植物大战僵尸：花园战争",
					year: "2014",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/81/ac/111297_GxY41.jpg",
					url: "https://bgm.tv/subject/111297",
					score: 6.6,
					tags: ["TPS", "EA", "多人"],
				},
				{
					id: "flowers-blooming-at-the-end-of-summer",
					title: "夏末盛开的花",
					year: "2021",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/3b/69/334753_2hU2R.jpg",
					url: "https://bgm.tv/subject/334753",
					score: 6.8,
					tags: ["视觉小说", "全年龄", "短篇"],
				},
				{
					id: "the-hungry-lamb",
					title: "饿殍：明末千里行",
					year: "2024",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/ff/61/448682_r6d8H.jpg",
					url: "https://bgm.tv/subject/448682",
					score: 6,
					tags: ["国产", "视觉小说", "历史"],
				},
				{
					id: "ori",
					title: "Ori",
					year: "2020",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/01/34/216896_I1nK0.jpg",
					url: "https://bgm.tv/subject/216896",
					score: 8,
					tags: ["横版", "ACT", "类银河城"],
				},
				{
					id: "rain-world",
					title: "雨世界",
					year: "2017",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/37/31/210885_mxd1g.jpg",
					url: "https://bgm.tv/subject/210885",
					score: 7.6,
					tags: ["生存", "独立游戏", "平台跳跃"],
				},
			],
		},
	],
};
