import type { GamesPageConfig } from "@/types/gameConfig";

export const gamesPageConfig: GamesPageConfig = {
	title: "游戏",
	titleEn: "Games",
	description: "记录玩过和正在玩的游戏",
	descriptionEn: "Games I have played and those I am playing now",
	categories: [
		{
			id: "gacha",
			name: "二游",
			nameEn: "Gacha Games",
			description: "“天河泄梦”",
			descriptionEn: "“Dreams spill from the celestial river”",
			icon: "material-symbols:auto-awesome-rounded",
			items: [
				{
					id: "genshin-impact",
					title: "原神",
					titleEn: "Genshin Impact",
					year: "2020",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/1a/22/284157_zgv97.jpg",
					url: "https://bgm.tv/subject/284157",
					score: 5.2,
					tags: ["miHoYo", "开放世界"],
					tagsEn: ["miHoYo", "Open world"],
				},
				{
					id: "honkai-star-rail",
					title: "崩坏：星穹铁道",
					titleEn: "Honkai: Star Rail",
					year: "2023",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/d2/c9/360097_z4dYA.jpg",
					url: "https://bgm.tv/subject/360097",
					score: 5.9,
					tags: ["miHoYo", "回合制"],
					tagsEn: ["miHoYo", "Turn-based"],
				},
				{
					id: "wuthering-waves",
					title: "鸣潮",
					titleEn: "Wuthering Waves",
					year: "2024",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/2e/ef/385208_shW2q.jpg",
					url: "https://bgm.tv/subject/385208",
					score: 6.2,
					tags: ["库洛游戏", "开放世界", "ARPG"],
					tagsEn: ["Kuro Games", "Open world", "ARPG"],
				},
				{
					id: "zenless-zone-zero",
					title: "绝区零",
					titleEn: "Zenless Zone Zero",
					year: "2024",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/90/24/380974_Kn8bt.jpg",
					url: "https://bgm.tv/subject/380974",
					score: 5.3,
					tags: ["miHoYo", "ACT"],
				},
				{
					id: "neverness-to-everness",
					title: "异环",
					titleEn: "Neverness to Everness",
					year: "2026",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/e7/1f/503983_6TzsC.jpg",
					url: "https://bgm.tv/subject/503983",
					score: 5.6,
					tags: ["开放世界", "PC"],
					tagsEn: ["Open world", "PC"],
				},
				{
					id: "honkai-impact-3rd",
					title: "崩坏3",
					titleEn: "Honkai Impact 3rd",
					year: "2016",
					status: "played",
					image: "/assets/games/honkai-impact-3rd.webp",
					url: "https://store.steampowered.com/app/1671200/",
					tags: ["miHoYo", "ACT", "二次元"],
					tagsEn: ["miHoYo", "Action", "Anime"],
				},
			],
		},
		{
			id: "aaa",
			name: "3A",
			nameEn: "AAA Games",
			description: "走过公路、神话与夜之城",
			descriptionEn: "Across open roads, mythic realms, and Night City",
			icon: "material-symbols:sports-esports-rounded",
			items: [
				{
					id: "forza-horizon-4",
					title: "极限竞速：地平线4",
					titleEn: "Forza Horizon 4",
					year: "2018",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/47/49/235675_MDomS.jpg",
					url: "https://bgm.tv/subject/235675",
					score: 7.9,
					tags: ["赛车", "PC", "开放世界"],
					tagsEn: ["Racing", "PC", "Open world"],
				},
				{
					id: "forza-horizon-5",
					title: "极限竞速：地平线5",
					titleEn: "Forza Horizon 5",
					year: "2021",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/53/b4/338909_ZBP7p.jpg",
					url: "https://bgm.tv/subject/338909",
					score: 7.5,
					tags: ["赛车", "PC", "开放世界"],
					tagsEn: ["Racing", "PC", "Open world"],
				},
				{
					id: "black-myth-wukong",
					title: "黑神话：悟空",
					titleEn: "Black Myth: Wukong",
					year: "2024",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/be/b4/313495_oVVzV.jpg",
					url: "https://bgm.tv/subject/313495",
					score: 7.8,
					tags: ["国产", "ARPG", "西游"],
					tagsEn: ["Made in China", "ARPG", "Journey to the West"],
				},
				{
					id: "cyberpunk-2077",
					title: "赛博朋克2077",
					titleEn: "Cyberpunk 2077",
					year: "2020",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/9a/c2/65759_fhutt.jpg",
					url: "https://bgm.tv/subject/65759",
					score: 7.4,
					tags: ["RPG", "PC", "开放世界"],
					tagsEn: ["RPG", "PC", "Open world"],
				},
				{
					id: "clair-obscur-expedition-33",
					title: "33号远征队：光与影",
					titleEn: "Clair Obscur: Expedition 33",
					year: "2025",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/41/87/498449_7Q9wH.jpg",
					url: "https://bgm.tv/subject/498449",
					score: 7.1,
					tags: ["JRPG", "回合制", "PC"],
					tagsEn: ["JRPG", "Turn-based", "PC"],
				},
				{
					id: "civilization-vi",
					title: "文明VI",
					titleEn: "Civilization VI",
					year: "2016",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/2f/38/182389_knNHp.jpg",
					url: "https://bgm.tv/subject/182389",
					score: 7.4,
					tags: ["SLG", "策略", "PC"],
					tagsEn: ["SLG", "Strategy", "PC"],
				},
				{
					id: "battlefield-2042",
					title: "战地2042",
					titleEn: "Battlefield 2042",
					year: "2021",
					status: "played",
					image: "/assets/games/battlefield-2042.webp",
					url: "https://store.steampowered.com/app/1517290/",
					tags: ["FPS", "多人", "战争"],
					tagsEn: ["FPS", "Multiplayer", "War"],
				},
				{
					id: "battlefield-v",
					title: "战地V",
					titleEn: "Battlefield V",
					year: "2018",
					status: "played",
					image: "/assets/games/battlefield-v.webp",
					url: "https://store.steampowered.com/app/1238810/",
					tags: ["FPS", "多人", "二战"],
					tagsEn: ["FPS", "Multiplayer", "World War II"],
				},
				{
					id: "left-4-dead",
					title: "求生之路",
					titleEn: "Left 4 Dead",
					year: "2008",
					status: "played",
					image: "/assets/games/left-4-dead.webp",
					url: "https://store.steampowered.com/app/500/",
					tags: ["FPS", "合作", "丧尸"],
					tagsEn: ["FPS", "Co-op", "Zombies"],
				},
				{
					id: "left-4-dead-2",
					title: "求生之路2",
					titleEn: "Left 4 Dead 2",
					year: "2009",
					status: "played",
					image: "/assets/games/left-4-dead-2.webp",
					url: "https://store.steampowered.com/app/550/",
					tags: ["FPS", "合作", "丧尸"],
					tagsEn: ["FPS", "Co-op", "Zombies"],
				},
				{
					id: "red-dead-redemption-2",
					title: "荒野大镖客：救赎2",
					titleEn: "Red Dead Redemption 2",
					year: "2018",
					status: "played",
					image: "/assets/games/red-dead-redemption-2.webp",
					url: "https://store.steampowered.com/app/1174180/",
					tags: ["开放世界", "西部", "冒险"],
					tagsEn: ["Open world", "Western", "Adventure"],
				},
				{
					id: "titanfall-2",
					title: "泰坦陨落2",
					titleEn: "Titanfall 2",
					year: "2016",
					status: "played",
					image: "/assets/games/titanfall-2.webp",
					url: "https://store.steampowered.com/app/1237970/",
					tags: ["FPS", "机甲", "科幻"],
					tagsEn: ["FPS", "Mechs", "Sci-fi"],
				},
				{
					id: "watch-dogs-2",
					title: "看门狗2",
					titleEn: "Watch Dogs 2",
					year: "2016",
					status: "played",
					image: "/assets/games/watch-dogs-2.webp",
					url: "https://store.steampowered.com/app/447040/",
					tags: ["开放世界", "黑客", "动作"],
					tagsEn: ["Open world", "Hacking", "Action"],
				},
				{
					id: "rainbow-six-siege",
					title: "彩虹六号：围攻",
					titleEn: "Tom Clancy's Rainbow Six Siege",
					year: "2015",
					status: "played",
					image: "/assets/games/rainbow-six-siege.webp",
					url: "https://store.steampowered.com/app/359550/",
					tags: ["FPS", "战术", "多人"],
					tagsEn: ["FPS", "Tactical", "Multiplayer"],
				},
				{
					id: "metro-2033-redux",
					title: "地铁2033：重制版",
					titleEn: "Metro 2033 Redux",
					year: "2014",
					status: "played",
					image: "/assets/games/metro-2033-redux.webp",
					url: "https://store.steampowered.com/app/286690/",
					tags: ["FPS", "末世", "剧情"],
					tagsEn: ["FPS", "Post-apocalyptic", "Story rich"],
				},
				{
					id: "detroit-become-human",
					title: "底特律：化身为人",
					titleEn: "Detroit: Become Human",
					year: "2018",
					status: "played",
					image: "/assets/games/detroit-become-human.webp",
					url: "https://store.steampowered.com/app/1222140/",
					tags: ["互动叙事", "科幻", "多结局"],
					tagsEn: ["Interactive narrative", "Sci-fi", "Multiple endings"],
				},
				{
					id: "death-stranding-2-on-the-beach",
					title: "死亡搁浅2：冥滩之上",
					titleEn: "DEATH STRANDING 2: ON THE BEACH",
					year: "2025",
					status: "played",
					image: "/assets/games/death-stranding-2-on-the-beach.webp",
					url: "https://store.steampowered.com/app/3280350/",
					tags: ["开放世界", "科幻", "冒险"],
					tagsEn: ["Open world", "Sci-fi", "Adventure"],
				},
				{
					id: "death-stranding-directors-cut",
					title: "死亡搁浅：导演剪辑版",
					titleEn: "DEATH STRANDING DIRECTOR'S CUT",
					year: "2021",
					status: "played",
					image: "/assets/games/death-stranding-directors-cut.webp",
					url: "https://store.steampowered.com/app/1850570/",
					tags: ["开放世界", "科幻", "冒险"],
					tagsEn: ["Open world", "Sci-fi", "Adventure"],
				},
				{
					id: "need-for-speed-heat",
					title: "极品飞车：热度",
					titleEn: "Need for Speed Heat",
					year: "2019",
					status: "played",
					image: "/assets/games/need-for-speed-heat.webp",
					url: "https://store.steampowered.com/app/1222680/",
					tags: ["赛车", "开放世界", "竞速"],
					tagsEn: ["Racing", "Open world", "Driving"],
				},
				{
					id: "nier-automata",
					title: "尼尔：机械纪元",
					titleEn: "NieR:Automata",
					year: "2017",
					status: "played",
					image: "/assets/games/nier-automata.webp",
					url: "https://store.steampowered.com/app/524220/",
					tags: ["ARPG", "科幻", "剧情"],
					tagsEn: ["ARPG", "Sci-fi", "Story rich"],
				},
			],
		},
		{
			id: "other",
			name: "其他游戏",
			nameEn: "Other Games",
			description: "我的”世界“",
			descriptionEn: "My “world”",
			icon: "material-symbols:stacks-rounded",
			trailingEllipsis: true,
			items: [
				{
					id: "minecraft",
					title: "Minecraft",
					year: "2011",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/ca/a0/12596_8YuNn.jpg",
					url: "https://bgm.tv/subject/12596",
					score: 8.9,
					tags: ["沙盒", "自由度", "PC"],
					tagsEn: ["Sandbox", "Creative freedom", "PC"],
				},
				{
					id: "undertale",
					title: "Undertale",
					year: "2015",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/68/52/147713_r51UK.jpg",
					url: "https://bgm.tv/subject/147713",
					score: 8.3,
					tags: ["RPG", "独立游戏", "像素"],
					tagsEn: ["RPG", "Indie", "Pixel art"],
				},
				{
					id: "monument-valley-series",
					title: "纪念碑谷（系列）",
					titleEn: "Monument Valley (Series)",
					year: "2014",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/a1/d1/101922_DZJzr.jpg",
					url: "https://bgm.tv/subject/101922",
					score: 7.8,
					tags: ["解谜", "独立游戏", "几何"],
					tagsEn: ["Puzzle", "Indie", "Geometry"],
				},
				{
					id: "spiderheck",
					title: "SpiderHeck",
					year: "2022",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/d8/72/402333_z806B.jpg",
					url: "https://bgm.tv/subject/402333",
					score: 7,
					tags: ["多人", "派对", "PC"],
					tagsEn: ["Multiplayer", "Party", "PC"],
				},
				{
					id: "terraria",
					title: "Terraria",
					year: "2011",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/59/ee/17852_7H99Q.jpg",
					url: "https://bgm.tv/subject/17852",
					score: 8.3,
					tags: ["沙盒", "独立游戏", "像素"],
					tagsEn: ["Sandbox", "Indie", "Pixel art"],
				},
				{
					id: "stardew-valley",
					title: "星露谷物语",
					titleEn: "Stardew Valley",
					year: "2016",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/f6/87/172808_rf2iX.jpg",
					url: "https://bgm.tv/subject/172808",
					score: 7.8,
					tags: ["模拟经营", "独立游戏", "像素"],
					tagsEn: ["Life sim", "Indie", "Pixel art"],
				},
				{
					id: "plants-vs-zombies-garden-warfare",
					title: "植物大战僵尸：花园战争",
					titleEn: "Plants vs. Zombies: Garden Warfare",
					year: "2014",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/81/ac/111297_GxY41.jpg",
					url: "https://bgm.tv/subject/111297",
					score: 6.6,
					tags: ["TPS", "EA", "多人"],
					tagsEn: ["TPS", "EA", "Multiplayer"],
				},
				{
					id: "flowers-blooming-at-the-end-of-summer",
					title: "夏末盛开的花",
					titleEn: "Flowers Blooming at the End of Summer",
					year: "2021",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/3b/69/334753_2hU2R.jpg",
					url: "https://bgm.tv/subject/334753",
					score: 6.8,
					tags: ["视觉小说", "全年龄", "短篇"],
					tagsEn: ["Visual novel", "All ages", "Short story"],
				},
				{
					id: "the-hungry-lamb",
					title: "饿殍：明末千里行",
					titleEn: "The Hungry Lamb: Traveling in the Late Ming Dynasty",
					year: "2024",
					status: "played",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/ff/61/448682_r6d8H.jpg",
					url: "https://bgm.tv/subject/448682",
					score: 6,
					tags: ["国产", "视觉小说", "历史"],
					tagsEn: ["Made in China", "Visual novel", "History"],
				},
				{
					id: "ori",
					title: "Ori",
					year: "2020",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/01/34/216896_I1nK0.jpg",
					url: "https://bgm.tv/subject/216896",
					score: 8,
					tags: ["横版", "ACT", "类银河城"],
					tagsEn: ["Side-scroller", "Action", "Metroidvania"],
				},
				{
					id: "rain-world",
					title: "雨世界",
					titleEn: "Rain World",
					year: "2017",
					status: "playing",
					image: "https://lain.bgm.tv/r/800/pic/cover/l/37/31/210885_mxd1g.jpg",
					url: "https://bgm.tv/subject/210885",
					score: 7.6,
					tags: ["生存", "独立游戏", "平台跳跃"],
					tagsEn: ["Survival", "Indie", "Platformer"],
				},
				{
					id: "plants-vs-zombies-battle-for-neighborville",
					title: "植物大战僵尸：和睦小镇保卫战",
					titleEn: "Plants vs. Zombies: Battle for Neighborville",
					year: "2019",
					status: "played",
					image:
						"/assets/games/plants-vs-zombies-battle-for-neighborville.webp",
					url: "https://store.steampowered.com/app/1262240/",
					tags: ["TPS", "多人", "EA"],
					tagsEn: ["TPS", "Multiplayer", "EA"],
				},
				{
					id: "war-thunder",
					title: "战争雷霆",
					titleEn: "War Thunder",
					year: "2013",
					status: "played",
					image: "/assets/games/war-thunder.webp",
					url: "https://store.steampowered.com/app/236390/",
					tags: ["载具", "多人", "战争"],
					tagsEn: ["Vehicles", "Multiplayer", "War"],
				},
				{
					id: "overcooked",
					title: "胡闹厨房",
					titleEn: "Overcooked",
					year: "2016",
					status: "played",
					image: "/assets/games/overcooked.webp",
					url: "https://store.steampowered.com/app/448510/",
					tags: ["合作", "派对", "烹饪"],
					tagsEn: ["Co-op", "Party", "Cooking"],
				},
				{
					id: "palworld",
					title: "幻兽帕鲁",
					titleEn: "Palworld",
					year: "2024",
					status: "played",
					image: "/assets/games/palworld.webp",
					url: "https://store.steampowered.com/app/1623730/",
					tags: ["开放世界", "生存", "合作"],
					tagsEn: ["Open world", "Survival", "Co-op"],
				},
				{
					id: "payday-2",
					title: "收获日2",
					titleEn: "PAYDAY 2",
					year: "2013",
					status: "played",
					image: "/assets/games/payday-2.webp",
					url: "https://store.steampowered.com/app/218620/",
					tags: ["FPS", "合作", "劫案"],
					tagsEn: ["FPS", "Co-op", "Heists"],
				},
				{
					id: "repo",
					title: "R.E.P.O.",
					titleEn: "R.E.P.O.",
					year: "2025",
					status: "played",
					image: "/assets/games/repo.webp",
					url: "https://store.steampowered.com/app/3241660/",
					tags: ["合作", "恐怖", "物理"],
					tagsEn: ["Co-op", "Horror", "Physics"],
				},
				{
					id: "tmodloader",
					title: "tModLoader",
					titleEn: "tModLoader",
					year: "2020",
					status: "played",
					image: "/assets/games/tmodloader.webp",
					url: "https://store.steampowered.com/app/1281930/",
					tags: ["模组工具", "泰拉瑞亚", "沙盒"],
					tagsEn: ["Modding tool", "Terraria", "Sandbox"],
				},
				{
					id: "war-robots",
					title: "战争机器人",
					titleEn: "War Robots",
					year: "2014",
					status: "played",
					image: "/assets/games/war-robots.webp",
					url: "https://store.steampowered.com/app/767560/",
					tags: ["机甲", "多人", "TPS"],
					tagsEn: ["Mechs", "Multiplayer", "TPS"],
				},
				{
					id: "the-binding-of-isaac-rebirth",
					title: "以撒的结合：重生",
					titleEn: "The Binding of Isaac: Rebirth",
					year: "2014",
					status: "played",
					image: "/assets/games/the-binding-of-isaac-rebirth.webp",
					url: "https://store.steampowered.com/app/250900/",
					tags: ["Roguelike", "独立游戏", "像素"],
					tagsEn: ["Roguelike", "Indie", "Pixel art"],
				},
				{
					id: "dyson-sphere-program",
					title: "戴森球计划",
					titleEn: "Dyson Sphere Program",
					year: "2021",
					status: "played",
					image: "/assets/games/dyson-sphere-program.webp",
					url: "https://store.steampowered.com/app/1366540/",
					tags: ["自动化", "太空", "建造"],
					tagsEn: ["Automation", "Space", "Building"],
				},
				{
					id: "hellslave",
					title: "Hellslave",
					titleEn: "Hellslave",
					year: "2022",
					status: "played",
					image: "/assets/games/hellslave.webp",
					url: "https://store.steampowered.com/app/1608450/",
					tags: ["RPG", "回合制", "暗黑"],
					tagsEn: ["RPG", "Turn-based", "Dark fantasy"],
				},
				{
					id: "breakout-13",
					title: "飞越13号房",
					titleEn: "Breakout 13",
					year: "2023",
					status: "played",
					image: "/assets/games/breakout-13.webp",
					url: "https://store.steampowered.com/app/2095300/",
					tags: ["互动影像", "国产", "剧情"],
					tagsEn: ["FMV", "Made in China", "Story rich"],
				},
				{
					id: "counter-strike-global-offensive",
					title: "反恐精英：全球攻势（现CS2）",
					titleEn: "Counter-Strike: Global Offensive (now CS2)",
					year: "2012",
					status: "played",
					image: "/assets/games/counter-strike-global-offensive.webp",
					url: "https://store.steampowered.com/app/730/",
					tags: ["FPS", "竞技", "多人"],
					tagsEn: ["FPS", "Competitive", "Multiplayer"],
				},
				{
					id: "counter-strike-condition-zero",
					title: "反恐精英：零点行动",
					titleEn: "Counter-Strike: Condition Zero",
					year: "2004",
					status: "played",
					image: "/assets/games/counter-strike-condition-zero.webp",
					url: "https://store.steampowered.com/app/80/",
					tags: ["FPS", "经典", "战术"],
					tagsEn: ["FPS", "Classic", "Tactical"],
				},
				{
					id: "dead-cells",
					title: "死亡细胞",
					titleEn: "Dead Cells",
					year: "2018",
					status: "played",
					image: "/assets/games/dead-cells.webp",
					url: "https://store.steampowered.com/app/588650/",
					tags: ["Roguelike", "平台跳跃", "独立游戏"],
					tagsEn: ["Roguelike", "Platformer", "Indie"],
				},
				{
					id: "deathmatch-classic",
					title: "Deathmatch Classic",
					titleEn: "Deathmatch Classic",
					year: "2001",
					status: "played",
					image: "/assets/games/deathmatch-classic.webp",
					url: "https://store.steampowered.com/app/40/",
					tags: ["FPS", "竞技", "经典"],
					tagsEn: ["FPS", "Competitive", "Classic"],
				},
				{
					id: "muse-dash",
					title: "喵斯快跑",
					titleEn: "Muse Dash",
					year: "2018",
					status: "played",
					image: "/assets/games/muse-dash.webp",
					url: "https://store.steampowered.com/app/774171/",
					tags: ["音游", "二次元", "节奏"],
					tagsEn: ["Music game", "Anime", "Rhythm"],
				},
			],
		},
	],
};
