import type { PlacePhoto, PlacesPageConfig } from "@/types/placesConfig";

/** 地点风景配图：本地缩略图、作者、原作与许可一起保存，非本人旅行照片。 */
function cover(
	id: string,
	alt: string,
	altEn: string,
	file: string,
	author: string,
	license: "CC BY 2.0" | "CC BY 3.0" | "CC BY-SA 3.0" | "CC BY-SA 4.0",
): PlacePhoto[] {
	const [, terms, version] = license.split(" ");
	return [
		{
			src: `/assets/images/places/${id}.jpg`,
			alt,
			altEn,
			credit: {
				author,
				sourceUrl: `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file.replaceAll(" ", "_"))}`,
				license,
				licenseUrl: `https://creativecommons.org/licenses/${terms.toLowerCase()}/${version}/`,
			},
		},
	];
}

const travel = [{ name: "旅行", nameEn: "Travel" }];
const china = { country: "中国", countryEn: "China" };
const australia = { country: "澳大利亚", countryEn: "Australia" };

// 足迹独立维护，不与相册、朋友圈或爱情树共用。
// 只记得月份/旬时使用 YYYY-MM + period；不要编造具体日期或停留时长。
export const placesConfig: PlacesPageConfig = {
	title: "去过的地方",
	titleEn: "Places I've been",
	description: "足迹地图与旅行记录，把走过的路慢慢收藏。",
	descriptionEn: "A little collection of journeys, places and memories.",
	previewWithExamples: false,
	places: [
		{
			id: "tasmania",
			name: "塔斯马尼亚",
			nameEn: "Tasmania",
			...australia,
			region: "塔斯马尼亚",
			regionEn: "Tasmania",
			city: "塔斯马尼亚",
			cityEn: "Tasmania",
			coordinates: [-42, 147],
			mapZoom: 6,
			tags: travel,
			visits: [{ start: "2026-05" }],
			note: "2026 年 5 月到访。暂按岛屿范围标注，具体城市与路线待补充。",
			noteEn:
				"Visited in May 2026. An island-level pin; cities and routes can be added later.",
			photos: cover(
				"tasmania",
				"塔斯马尼亚摇篮山与鸽湖风景配图",
				"Scenery cover: Cradle Mountain and Dove Lake, Tasmania",
				"Boat shed and Cradle Mountain at Dove Lake, Tas.jpg",
				"Thennicke",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "xian",
			name: "西安",
			nameEn: "Xi'an",
			...china,
			region: "陕西",
			regionEn: "Shaanxi",
			city: "西安",
			cityEn: "Xi'an",
			coordinates: [34.261, 108.942],
			tags: travel,
			visits: [{ start: "2026-04-15" }],
			note: "2026 年 4 月 15 日的西安足迹。",
			noteEn: "A visit to Xi'an on 15 April 2026.",
			photos: cover(
				"xian",
				"西安城墙风景配图",
				"Scenery cover: Xi'an city wall",
				"City wall of Xi'an 51550-Xian (27959363326).jpg",
				"xiquinhosilva",
				"CC BY 2.0",
			),
		},
		{
			id: "chengdu",
			name: "成都",
			nameEn: "Chengdu",
			...china,
			region: "四川",
			regionEn: "Sichuan",
			city: "成都",
			cityEn: "Chengdu",
			coordinates: [30.66, 104.063],
			tags: travel,
			visits: [{ start: "2026-04-10" }, { start: "2025-05", period: "early" }],
			note: "两次到访：2025 年 5 月上旬、2026 年 4 月 10 日。",
			noteEn: "Two visits: early May 2025 and 10 April 2026.",
			photos: cover(
				"chengdu",
				"成都城市与远处雪山风景配图",
				"Scenery cover: Chengdu skyline and distant mountains",
				"在成都遥望雪山 Chengdu skyline with a view of Mount Siguniang.jpg",
				"书剑飘零",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "jiuzhaigou",
			name: "九寨沟",
			nameEn: "Jiuzhaigou",
			...china,
			region: "四川",
			regionEn: "Sichuan",
			city: "阿坝",
			cityEn: "Aba",
			coordinates: [33.2, 103.9],
			mapZoom: 10,
			tags: travel,
			visits: [{ start: "2026-04", period: "early" }],
			note: "2026 年 4 月初到访，具体日期待补充。",
			noteEn: "Visited in early April 2026; the exact date is not recorded.",
			photos: cover(
				"jiuzhaigou",
				"九寨沟湖泊风景配图",
				"Scenery cover: a lake in Jiuzhaigou",
				"Lake in Jiuzhaigou.jpg",
				"MSK",
				"CC BY-SA 3.0",
			),
		},
		{
			id: "xiamen",
			name: "厦门",
			nameEn: "Xiamen",
			...china,
			region: "福建",
			regionEn: "Fujian",
			city: "厦门",
			cityEn: "Xiamen",
			coordinates: [24.48, 118.089],
			tags: travel,
			visits: [{ start: "2026-03", period: "late" }],
			note: "2026 年 3 月下旬的厦门足迹。",
			noteEn: "A visit to Xiamen in late March 2026.",
			photos: cover(
				"xiamen",
				"厦门中山路街景配图",
				"Scenery cover: Zhongshan Road, Xiamen",
				"Zhongshan Road, Xiamen 11.jpg",
				"Slyronit",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "chaozhou",
			name: "潮州",
			nameEn: "Chaozhou",
			...china,
			region: "广东",
			regionEn: "Guangdong",
			city: "潮州",
			cityEn: "Chaozhou",
			coordinates: [23.658, 116.622],
			tags: travel,
			visits: [{ start: "2026-03", period: "mid" }],
			note: "2026 年 3 月中旬的潮汕行程，潮州这一站。",
			noteEn: "The Chaozhou stop of a Chaoshan trip in mid-March 2026.",
			photos: cover(
				"chaozhou",
				"潮州广济桥风景配图",
				"Scenery cover: Guangji Bridge, Chaozhou",
				"Guangji Bridge.JPG",
				"小杰杰",
				"CC BY 3.0",
			),
		},
		{
			id: "shantou",
			name: "汕头",
			nameEn: "Shantou",
			...china,
			region: "广东",
			regionEn: "Guangdong",
			city: "汕头",
			cityEn: "Shantou",
			coordinates: [23.354, 116.682],
			tags: travel,
			visits: [{ start: "2026-03", period: "mid" }],
			note: "2026 年 3 月中旬的潮汕行程，汕头这一站。",
			noteEn: "The Shantou stop of a Chaoshan trip in mid-March 2026.",
			photos: cover(
				"shantou",
				"汕头港湾与城市风景配图",
				"Scenery cover: Shantou harbour and skyline",
				"Shantou harbour and skyline viewed from Double Island June 2022.jpg",
				"Puekai",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "wollongong",
			name: "卧龙岗",
			nameEn: "Wollongong",
			...australia,
			region: "新南威尔士",
			regionEn: "New South Wales",
			city: "卧龙岗",
			cityEn: "Wollongong",
			coordinates: [-34.427, 150.894],
			tags: travel,
			visits: [{ start: "2025-11" }],
			note: "2025 年 11 月到访澳大利亚卧龙岗。",
			noteEn: "Visited Wollongong, Australia in November 2025.",
			photos: cover(
				"wollongong",
				"卧龙岗海岸与灯塔风景配图",
				"Scenery cover: Wollongong coastline and lighthouse",
				"Wollongong Head February 2021.jpg",
				"Hellobook",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "guangzhou",
			name: "广州",
			nameEn: "Guangzhou",
			...china,
			region: "广东",
			regionEn: "Guangdong",
			city: "广州",
			cityEn: "Guangzhou",
			coordinates: [23.13, 113.26],
			tags: travel,
			visits: [{ start: "2025-08", period: "late" }],
			note: "2025 年 8 月底到访广州。",
			noteEn: "Visited Guangzhou at the end of August 2025.",
			photos: cover(
				"guangzhou",
				"广州珠江与广州塔风景配图",
				"Scenery cover: the Pearl River and Canton Tower, Guangzhou",
				"Pearl River Canton Tower (cropped).JPG",
				"Gzdavidwong",
				"CC BY-SA 3.0",
			),
		},
		{
			id: "shenzhen",
			name: "深圳",
			nameEn: "Shenzhen",
			...china,
			region: "广东",
			regionEn: "Guangdong",
			city: "深圳",
			cityEn: "Shenzhen",
			coordinates: [22.547, 114.054],
			tags: travel,
			visits: [{ start: "2025-08", period: "late" }],
			note: "2025 年 8 月底到访深圳。",
			noteEn: "Visited Shenzhen at the end of August 2025.",
			photos: cover(
				"shenzhen",
				"深圳城市天际线风景配图",
				"Scenery cover: Shenzhen skyline",
				"TOP OF THE DIWANG BUILDING SEE SHENZHEN SKYLINE (33).jpg",
				"Dinkun Chen",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "guilin",
			name: "桂林",
			nameEn: "Guilin",
			...china,
			region: "广西",
			regionEn: "Guangxi",
			city: "桂林",
			cityEn: "Guilin",
			coordinates: [25.275, 110.296],
			tags: travel,
			visits: [{ start: "2025-08" }],
			note: "2025 年 8 月的桂林足迹，具体日期待补充。",
			noteEn: "Visited Guilin in August 2025; the exact date is not recorded.",
			photos: cover(
				"guilin",
				"桂林漓江山水风景配图",
				"Scenery cover: the Li River landscape, Guilin",
				"1 li jiang guilin yangshuo 2011.jpg",
				"chensiyuan",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "chongqing",
			name: "重庆",
			nameEn: "Chongqing",
			...china,
			region: "重庆",
			regionEn: "Chongqing",
			city: "重庆",
			cityEn: "Chongqing",
			coordinates: [29.564, 106.55],
			tags: travel,
			visits: [{ start: "2025-05", period: "late" }, { start: "2018-07" }],
			note: "两次到访：2018 年 7 月、2025 年 5 月下旬。",
			noteEn: "Two visits: July 2018 and late May 2025.",
			photos: cover(
				"chongqing",
				"重庆城市风景配图",
				"Scenery cover: Chongqing skyline",
				"Chongqing center.jpg",
				"Oliver Ren",
				"CC BY-SA 3.0",
			),
		},
		{
			id: "beijing",
			name: "北京",
			nameEn: "Beijing",
			...china,
			region: "北京",
			regionEn: "Beijing",
			city: "北京",
			cityEn: "Beijing",
			coordinates: [39.907, 116.398],
			tags: travel,
			visits: [{ start: "2025-05", period: "early" }],
			note: "2025 年 5 月上旬到访北京。",
			noteEn: "Visited Beijing in early May 2025.",
			photos: cover(
				"beijing",
				"北京故宫建筑风景配图",
				"Scenery cover: the Forbidden City, Beijing",
				"Forbidden City Panorama 1.jpg",
				"Tojan76",
				"CC BY-SA 3.0",
			),
		},
		{
			id: "hubei",
			name: "湖北",
			nameEn: "Hubei",
			...china,
			region: "湖北",
			regionEn: "Hubei",
			city: "省级足迹",
			cityEn: "Province-level record",
			coordinates: [31, 112.3],
			mapZoom: 6,
			tags: travel,
			visits: [{ start: "2025-03" }],
			note: "2025 年 3 月到访湖北。暂按省份范围标注，具体城市待补充。",
			noteEn:
				"Visited Hubei in March 2025. An indicative province-level pin; the city can be added later.",
			photos: cover(
				"hubei",
				"湖北武汉东湖与磨山风景配图（非具体到访记录）",
				"Scenery cover: East Lake and Mount Mo, Hubei; not a specific visit record",
				"Mount Mo and East Lake, Wuhan.jpg",
				"Zheng Zhou",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "jiujiang",
			name: "九江",
			nameEn: "Jiujiang",
			...china,
			region: "江西",
			regionEn: "Jiangxi",
			city: "九江",
			cityEn: "Jiujiang",
			coordinates: [29.661, 115.954],
			tags: travel,
			visits: [{ start: "2025-02" }],
			note: "2025 年 2 月的江西行程，标注在九江。",
			noteEn: "The Jiangxi trip in February 2025, recorded in Jiujiang.",
			photos: cover(
				"jiujiang",
				"九江城市风景配图",
				"Scenery cover: Jiujiang city",
				"Jiujiang Skyview.jpg",
				"Gweilo60",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "hulunbuir",
			name: "呼伦贝尔",
			nameEn: "Hulunbuir",
			...china,
			region: "内蒙古",
			regionEn: "Inner Mongolia",
			city: "呼伦贝尔",
			cityEn: "Hulunbuir",
			coordinates: [49.207, 119.771],
			mapZoom: 8,
			tags: travel,
			visits: [{ start: "2023-08" }],
			note: "2023 年 8 月到访呼伦贝尔，暂按城市范围标注。",
			noteEn:
				"Visited Hulunbuir in August 2023; the pin represents the city area.",
			photos: cover(
				"hulunbuir",
				"呼伦贝尔草原风景配图",
				"Scenery cover: Hulunbuir grasslands",
				"Hulunbuir Grasslands, Inner Mongolia.jpg",
				"Sergio Tittarini",
				"CC BY 2.0",
			),
		},
		{
			id: "perth",
			name: "珀斯",
			nameEn: "Perth",
			...australia,
			region: "西澳大利亚",
			regionEn: "Western Australia",
			city: "珀斯",
			cityEn: "Perth",
			coordinates: [-31.952, 115.861],
			tags: travel,
			visits: [{ start: "2019-08" }],
			note: "2019 年 8 月到访澳大利亚珀斯。",
			noteEn: "Visited Perth, Australia in August 2019.",
			photos: cover(
				"perth",
				"珀斯伊丽莎白码头桥与城市风景配图",
				"Scenery cover: Elizabeth Quay Bridge and Perth skyline",
				"Perth (AU), Elizabeth Quay Bridge -- 2019 -- 0346-8 (crop 2).jpg",
				"Dietmar Rabich",
				"CC BY-SA 4.0",
			),
		},
		{
			id: "yibin",
			name: "宜宾",
			nameEn: "Yibin",
			...china,
			region: "四川",
			regionEn: "Sichuan",
			city: "宜宾",
			cityEn: "Yibin",
			coordinates: [28.752, 104.643],
			tags: travel,
			visits: [{ start: "2018-07" }],
			note: "2018 年 7 月的宜宾足迹，具体日期待补充。",
			noteEn: "Visited Yibin in July 2018; the exact date is not recorded.",
			photos: cover(
				"yibin",
				"宜宾城市风景配图",
				"Scenery cover: Yibin city",
				"Yibin birdview.jpg",
				"Terence85",
				"CC BY-SA 3.0",
			),
		},
		{
			id: "kensington",
			name: "肯辛顿 · 现居",
			nameEn: "Kensington · current location",
			...australia,
			region: "新南威尔士",
			regionEn: "New South Wales",
			city: "悉尼",
			cityEn: "Sydney",
			coordinates: [-33.908, 151.226],
			mapZoom: 13,
			currentLocation: true,
			tags: [{ name: "现居", nameEn: "Current location" }],
			visits: [],
			note: "悉尼 Kensington（肯辛顿）。仅标注社区范围，不展示具体住址；不计为一次旅行。",
			noteEn:
				"Based in Kensington, Sydney. A suburb-level location only, without a residential address or an invented trip date.",
			photos: cover(
				"kensington",
				"悉尼肯辛顿 Anzac Parade 街景配图",
				"Scenery cover: Anzac Parade, Kensington, Sydney",
				"Anzac Parade Kensington 001aa.jpg",
				"Sardaka",
				"CC BY-SA 4.0",
			),
		},
	],
	examples: [],
	map: {
		center: [5, 130],
		zoom: 3,
		tileUrl: "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
		attribution:
			'&copy; <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap</a> contributors',
	},
};
